### ISSUE TITLE
About the installation problem.

### ISSUE THREAD

**Issue by Tsugikuni-Yoriichi** [lmb-freiburg/flownet2-docker#14]
I have tested your project before. It give me good result.
But now while for a new computer, I met problems. I have installed all the things I think. But while input the command to run the test, it just give me result very quickly even without time cost.

while I type in the command:
sudo ./run-network.sh -n FlowNet2 -v data/0000000-imgL.png data/0000001-imgL.png flow.flo

it gives me feedback of: 
Using GPU:       0
Running network: FlowNet2
Working dir:     /flownet2/flownet2/scripts
First input:     data/0000000-imgL.png
Second input:    data/0000001-imgL.png
Output:          flow.flo

But it takes no time to load paramters and I can't find flow.flo file.

My docker version is:
Docker version 19.03.5

Docker images:
REPOSITORY          TAG                            IMAGE ID            CREATED             SIZE
flownet2            latest                         c98d87d4f617        4 minutes ago       8.14GB
nvidia/cuda         8.0-cudnn5-devel-ubuntu16.04   db7f23a9ae16        7 weeks ago         1.85GB

NVIDIA and gpu information:
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GTX 980
Result = PASS

It is quite strange and I have tried many times. Problem is still here.

**Comment by Damax18** [comment]
hi @WANGLXUE , i met the same problem, how did you slove it? Thanks~

**Comment by WANGYuSCU** [comment]
Sorry, it has been a long time. This problem can be solved in some way. But I can not figure out how for now.
What I remember about Flownet and docker is that there may be some requirement on the version of docker and maybe even ubuntu. I am using ubuntu16.04 in the last.
I remember I have also changed docker version because some docker version seem can not support this Flownet. I am not familiar with docker. I don't know if the Flownet2 rely on the nvidia driver of ubuntu or nvidia driver of the docker. Anyway, please find the right nvidia driver both in ubuntu or in docker nvidia.  You can find the information in the instructions "**an Ubuntu 16.04 base extended by Nvidia, with CUDA 8.0**". 
I have just changed my job and will later use Flownet to do some other work. I will check it when my new pc arrived the next week. Good luck.
