### ISSUE TITLE
make error while building on docker.

### ISSUE THREAD

**Issue by aiwithshekhar** [lmb-freiburg/flownet2-docker#21]
Hi, i was try to build it using docker on my windows machine using make, after some time i get below error.
Can you please help me with this!!
![image](https://user-images.githubusercontent.com/31220538/90321189-0530da00-df65-11ea-9a50-693696875b82.png)

**Comment by nikolausmayer** [comment]
[This](https://github.com/lmb-freiburg/flownet2-docker/blob/master/Dockerfile#L19) is where the user `flownet` is created in the Dockerfile. I have no experience with how WSL oder other linux-on-windows environments deal with user creation, but you can just replace that part of the Dockerfile with whatever works for you. This user does not need any permissions, it just maps your host-UID/GID into the container so that the files which are produced by the container correctly belong to you.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
